server:
  port: 9090

# Camunda Platform 7
camunda:
  bpm:
    client:
      base-url: ${CAMUNDA_BASE_URL:http://localhost:8080/engine-rest}
      disable-backoff-strategy: true

# Clockify
clockify:
  apiKey: "<API-KEY>"

# HRWorks
hrworks:
  accessKey: "<ACCESS-KEY>"
  secretAccessKey: "<SECRET-ACCESS-KEY>"
